name: Construir y publicar imagen Docker para múltiples plataformas

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Iniciar sesión en ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir y publicar imagen para múltiples plataformas
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/laBatcueva/cpanel-server:latest
          platforms: linux/amd64,linux/arm/v7
